#!/usr/bin/env python

''' This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.'''

import os, sys
sys.path.append (os.getcwd() + "../../tools/waf")
import jemu, juce

libjemu = bld.shlib (
    source      = bld.path.ant_glob ('src/**/*.cpp'),
    includes    = ['.'],
    use         = [],
    env         = bld.env.derive(),
    target      = '../../dist/lib/jemu',
    name        = 'JEMU',
    vnum        = '0.0.1'
)

if juce.is_mac():
    libjemu.source += bld.path.ant_glob ('src/**/*.mm')
    libjemu.linkflags = ['-install_name', '@rpath/libjemu.dylib',
                         '-Wl,-compatibility_version,0.0.0', '-Wl,-current_version,0.0.1']
    libjemu.install_path = None
